### ISSUE TITLE
Ingame Ui broken after dump

### ISSUE THREAD

**Issue by ramisotti** [kiraio-moe/FiveHeartsTranslation#1]
When I dump the files, the in-game UI is broken, and nothing can be selected. I tested it with the original dump files without making any changes to the .json files.
![five_Bug](https://github.com/user-attachments/assets/f1bfb4b5-7e46-4b12-ae06-ad11bd91d021)

**Comment by kiraio-moe** [comment]
This patch didn't interfere with anything except replacing the TextAsset resources. That bug is likely occurred by the game itself.

Normal:
![image](https://github.com/user-attachments/assets/d7934456-ddbe-4e97-be6f-6425b609b4f9)

**Comment by ramisotti** [comment]
Okay, strange. If I remove the OBJECT_100.json, everything works again. But if I delete this OBJECT_XXX.json, I won't be able to translate anything anymore.

**Comment by kiraio-moe** [comment]
> Okay, strange. If I remove the OBJECT_100.json, everything works again. But if I delete this OBJECT_XXX.json, I won't be able to translate anything anymore.

Don't replace/patch any text assets that doesn't contains translation (except you know what you're doing). It will lead to unexpected behavior.

**Comment by ramisotti** [comment]
I didn't change anything. Here's the .json file from the dump. To load the patch, everything needs to go into this folder structure, right? \Mods\Patches\TextAsset

[OBJECT_100.json](https://github.com/user-attachments/files/17965255/OBJECT_100.json)

**Comment by kiraio-moe** [comment]
> I didn't change anything. Here's the .json file from the dump. 
> [OBJECT_100.json](https://github.com/user-attachments/files/17965255/OBJECT_100.json)

Maybe the game unable to parse some data.

> To load the patch, everything needs to go into this folder structure, right? \Mods\Patches\TextAsset

Yep, not other ways.
